# Exploration du jeu de données : *ccfraud_dataset1.csv*

## Explication du dataset

Ce jeu de données regroupe les transactions bancaires effectuées en septembre 2013 par des citoyens européens détenteurs d'une carte de crédit. Toutes ces transactions ont ainsi eu lieu en l'espace de deux jours.

Par soucis de confidentialité, les données concernant les clients des banques n'ont pas pu être révélés dans le jeu de données. Ainsi, elles ont été remplacés par les composantes principales `V1`,`V2`, ...,`V28` par transformation par ACP.

Les seules colonnes non transformées sont :

* `Time` : Le temps passé (*en secondes*) depuis la première transaction enregistrée dans le jeu de données.
* `Amount` : Le montant de la transaction (*en €*)
* `Class` : Un booléen qui indique si la transaction est une fraude ou non. **1** si c'est une fraude, **0** si elle est légitime.

## Activation de l'environnement virtuel

In [9]:
!source ../venv/bin/activate

## Import des librairies

In [2]:
import pandas as pd

## Import du jeu de données

In [3]:
df = pd.read_csv("../data/ccfraud_dataset1.csv")

## Data Viz

In [5]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
df_reduced = df.copy()
df_reduced = df_reduced[['Time','Amount','Class']]

df_reduced.head(3)

   Time  Amount  Class
0   0.0  149.62      0
1   0.0    2.69      0
2   1.0  378.66      0

In [21]:
df_reduced['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

> 1 signifie que la transaction est frauduleuse, 0 si elle est légitime

In [26]:
fraud_percent = float((df_reduced['Class'].value_counts()[1] / df_reduced['Class'].value_counts()[0]) * 100) 
print(f"Pourcentage de fraude dans le dataset : {fraud_percent:.2f} %")

Pourcentage de fraude dans le dataset : 0.17 %

In [ ]:
last_time_s = int(df_reduced['Time'].tail(1).iloc[0])

172792

> La colonne `Time` indique le temps passé depuis la première transaction du dataset, en **secondes**. Ces données sont les données de septembre 2013.

La dernière transaction a eu lieu 172 792 secondes après la première.